### PR TITLE
Update to v0.14.0-rc3

### PR DESCRIPTION
**Pull request by JordanMartinez**
Backlinking to purescript-contrib/governance#35

### CODE REVIEW

**Comment by JordanMartinez** [comment]
This should pass CI. If there's an error here, then something still isn't right in my bash script.

**Comment by thomashoneyman** [comment]
```
[1/1 ModuleNotFound] .spago/numbers/master/src/Data/Number.purs:10:1

  10  import Data.Function.Uncurried (Fn4, runFn4)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Module Data.Function.Uncurried was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```

**Comment by JordanMartinez** [comment]
Nah. Package set didn't include `functions` in the `numbers` package's dependencies. I fixed that just now. CI should pass once I restart the build.

**Comment by thomashoneyman** [comment]
This looks good other than reverting the whitespace changes to the ci.yml file!

**Comment by JordanMartinez** [comment]
CI passes.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
